### ISSUE TITLE
yarn build:release makes TypeErr

### ISSUE THREAD

**Issue by dokang89** [seed-rs/seed-quickstart-webpack#27]
I cloned this template by `use this template` and typed
`yarn build:release`

It prints error below
```
    ERROR in ./css/styles.css (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??ref--7-2!./css/styles.css)
    Module build failed (from ./node_modules/postcss-loader/src/index.js):
    TypeError: usedCssClassesInFile.map(...).flat is not a function
        at files.forEach.filePath (/home/dokang/projects/furiosa/practice_arch/node_modules/postcss-typed-css-classes/index.js:314:24)
        at Array.forEach (<anonymous>)
        at content.forEach (/home/dokang/projects/furiosa/practice_arch/node_modules/postcss-typed-css-classes/index.js:306:13)
        at Array.forEach (<anonymous>)
        at getAndFilterParsedClassesWithOpts (/home/dokang/projects/furiosa/practice_arch/node_modules/postcss-typed-css-classes/index.js:304:13)
        at /home/dokang/projects/furiosa/practice_arch/node_modules/postcss-typed-css-classes/index.js:59:24
        at LazyResult.run (/home/dokang/projects/furiosa/practice_arch/node_modules/postcss/lib/lazy-result.js:288:14)
        at LazyResult.asyncTick (/home/dokang/projects/furiosa/practice_arch/node_modules/postcss/lib/lazy-result.js:212:26)
        at LazyResult.asyncTick (/home/dokang/projects/furiosa/practice_arch/node_modules/postcss/lib/lazy-result.js:225:14)
        at /home/dokang/projects/furiosa/practice_arch/node_modules/postcss/lib/lazy-result.js:217:17
```

ubuntu 20.04
node v10.19.0
yarn 1.19.1
rustc 1.46.0

`yarn start` or `yarn build` works well

**Comment by dokang89** [comment]
Oh I succeeded with node 14
